# Generated by Django 2.0.7 on 2018-11-07 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eletricista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('CEP', models.CharField(max_length=20)),
                ('CPF', models.CharField(max_length=14, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=12)),
                ('foto', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(default='', max_length=10)),
                ('bloqueado', models.CharField(default='False', max_length=10)),
                ('nota', models.DecimalField(decimal_places=3, default='w/e', max_digits=5)),
                ('usuario', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(default=None)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('eletricista_avaliado', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='eletricista.Eletricista')),
            ],
        ),
    ]
