# Generated by Django 2.0.7 on 2018-11-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletricista',
            name='id',
        ),
        migrations.AlterField(
            model_name='eletricista',
            name='nota',
            field=models.DecimalField(decimal_places=3, default='w/e', max_digits=5, primary_key=True, serialize=False),
        ),
    ]
