# Generated by Django 2.0.7 on 2018-11-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0002_auto_20181107_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletricista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eletricista',
            name='nota',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
