# Generated by Django 2.0.7 on 2018-11-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0003_auto_20181107_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletricista',
            name='nota',
            field=models.FloatField(default='w/e'),
        ),
    ]
