# Generated by Django 2.0.7 on 2018-11-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0004_auto_20181108_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletricista',
            name='nota',
            field=models.FloatField(),
        ),
    ]
