# Generated by Django 2.0.7 on 2018-11-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0005_auto_20181108_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletricista',
            name='id',
        ),
        migrations.AlterField(
            model_name='eletricista',
            name='nota',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
