# Generated by Django 2.0.7 on 2018-11-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0006_auto_20181108_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletricista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eletricista',
            name='nota',
            field=models.FloatField(default=None),
        ),
    ]
