# Generated by Django 2.0.7 on 2018-11-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0007_auto_20181108_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletricista',
            name='nota',
            field=models.FloatField(default=None, null=True),
        ),
    ]
