# Generated by Django 2.0.7 on 2018-11-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0008_auto_20181108_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletricista',
            name='nota',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True),
        ),
    ]
