# Generated by Django 2.0.7 on 2018-11-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletricista', '0009_auto_20181108_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eletricista',
            old_name='nota',
            new_name='notaElec',
        ),
    ]
