# Generated by Django 2.0.7 on 2018-11-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDeServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('eletricista', models.CharField(max_length=100)),
                ('status', models.CharField(default='w/e', max_length=100, null=True, verbose_name='Status')),
            ],
        ),
    ]
