# Generated by Django 2.0.7 on 2018-10-18 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDeServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2018, 10, 18, 11, 38, 23, 743103), verbose_name='Data da solicitação')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('eletricista', models.CharField(max_length=100)),
                ('status', models.CharField(default='w/e', max_length=100, verbose_name='Status')),
            ],
        ),
    ]
