# Generated by Django 2.0.7 on 2018-10-18 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 11, 38, 32, 243740), verbose_name='Data da solicitação'),
        ),
    ]
