# Generated by Django 2.0.7 on 2018-10-18 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0002_auto_20181018_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 11, 40, 42, 690185), verbose_name='Data da solicitação'),
        ),
        migrations.AlterField(
            model_name='pedidodeservico',
            name='status',
            field=models.CharField(default='w/e', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
