# Generated by Django 2.0.7 on 2018-10-18 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0003_auto_20181018_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodeservico',
            name='status',
        ),
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 11, 42, 20, 822776), verbose_name='Data da solicitação'),
        ),
    ]
