# Generated by Django 2.0.7 on 2018-10-18 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0005_auto_20181018_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 11, 44, 57, 475776), verbose_name='Data da solicitação'),
        ),
    ]
