# Generated by Django 2.0.7 on 2018-10-21 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0006_auto_20181018_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 18, 29, 50, 298304), verbose_name='Data da solicitação'),
        ),
    ]
