# Generated by Django 2.0.7 on 2018-10-21 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0007_auto_20181021_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 18, 32, 33, 849659), verbose_name='Data da solicitação'),
        ),
    ]
