# Generated by Django 2.0.7 on 2018-10-22 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0010_auto_20181022_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 17, 1, 40, 486565), verbose_name='Data da solicitação'),
        ),
    ]
