# Generated by Django 2.0.7 on 2018-10-22 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0023_auto_20181022_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 17, 12, 44, 702556), verbose_name='Data da solicitação'),
        ),
    ]
