# Generated by Django 2.0.7 on 2018-10-22 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0026_auto_20181022_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 18, 21, 1, 914903), verbose_name='Data da solicitação'),
        ),
    ]
