# Generated by Django 2.0.7 on 2018-10-25 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0027_auto_20181022_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 13, 15, 52, 483051), verbose_name='Data da solicitação'),
        ),
    ]
