# Generated by Django 2.0.7 on 2018-10-29 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0031_auto_20181025_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 10, 4, 10, 565369), verbose_name='Data da solicitação'),
        ),
    ]
