# Generated by Django 2.0.7 on 2018-10-29 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0036_auto_20181029_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 10, 36, 50, 481470), verbose_name='Data da solicitação'),
        ),
    ]
