# Generated by Django 2.0.7 on 2018-10-30 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0037_auto_20181029_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 15, 18, 14, 592797), verbose_name='Data da solicitação'),
        ),
    ]
