# Generated by Django 2.0.7 on 2018-10-30 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0038_auto_20181030_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 16, 43, 34, 810657), verbose_name='Data da solicitação'),
        ),
    ]
