# Generated by Django 2.0.7 on 2018-11-07 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0038_auto_20181030_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 20, 4, 10, 931138), verbose_name='Data da solicitação'),
        ),
    ]
