# Generated by Django 2.0.7 on 2018-11-01 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0039_auto_20181030_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 15, 35, 1, 894654), verbose_name='Data da solicitação'),
        ),
    ]
