# Generated by Django 2.0.7 on 2018-11-05 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0040_auto_20181101_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 15, 55, 37, 21573), verbose_name='Data da solicitação'),
        ),
    ]
