# Generated by Django 2.0.7 on 2018-11-07 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0040_auto_20181107_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 20, 6, 12, 351816), verbose_name='Data da solicitação'),
        ),
    ]
