# Generated by Django 2.0.7 on 2018-11-07 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0041_auto_20181107_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 20, 7, 41, 744440), verbose_name='Data da solicitação'),
        ),
    ]
