# Generated by Django 2.0.7 on 2018-11-05 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0041_auto_20181105_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 16, 2, 56, 78686), verbose_name='Data da solicitação'),
        ),
    ]
