# Generated by Django 2.0.7 on 2018-11-05 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0042_auto_20181105_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 16, 3, 23, 628261), verbose_name='Data da solicitação'),
        ),
    ]
