# Generated by Django 2.0.7 on 2018-11-06 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0043_auto_20181105_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 14, 44, 19, 490724), verbose_name='Data da solicitação'),
        ),
    ]
