# Generated by Django 2.0.7 on 2018-11-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0043_auto_20181107_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodeservico',
            name='data',
        ),
    ]
