# Generated by Django 2.0.7 on 2018-11-06 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0044_auto_20181106_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 14, 44, 39, 781885), verbose_name='Data da solicitação'),
        ),
    ]
