# Generated by Django 2.0.7 on 2018-11-08 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0045_auto_20181106_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 15, 30, 20, 365701), verbose_name='Data da solicitação'),
        ),
    ]
