# Generated by Django 2.0.7 on 2018-11-12 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0046_auto_20181108_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 14, 46, 53, 475390), verbose_name='Data da solicitação'),
        ),
    ]
