# Generated by Django 2.0.7 on 2018-11-08 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0046_auto_20181108_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 19, 4, 58, 78278), verbose_name='Data da solicitação'),
        ),
    ]
