# Generated by Django 2.0.7 on 2018-11-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0044_remove_pedidodeservico_data'),
        ('PedidoDeServico', '0046_auto_20181108_1530'),
    ]

    operations = [
    ]
