# Generated by Django 2.0.7 on 2018-11-08 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoDeServico', '0047_auto_20181108_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeservico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 19, 5, 48, 379307), verbose_name='Data da solicitação'),
        ),
    ]
